USE student_db;
-- PRACTICE SET 1
CREATE TABLE students1(
stu_id INT PRIMARY KEY,
name VARCHAR(50),
branch VARCHAR(50),
marks INT
);
-- TASKS
-- INSERT 5 STUDENTS
INSERT INTO students1
VALUES
(101,"STEVE","MECH",90),
(102,"NANCY","EEE",80),
(103,"JONATHAN","MECH",85),
(104,"ELEVEN","ECE",90),
(105,"DUSTIN","MECH",70);
-- DISPLAY ALL STUDENTS
SELECT * FROM students1;
-- DISPLAY ONLY NAMES AND MARKS
SELECT name,marks from students1;
-- FIND STUDENTS WITH MARKS > 80
SELECT * FROM students1 WHERE marks > 80;
-- FIND PARTICULAR BRANCH STUDENTS
SELECT * FROM students1 WHERE branch = "CSE";
SELECT * FROM students1 WHERE branch = "MECH";
-- INCREASE MARKS BY 5 FOR ALL STUDENTS
SET SQL_SAFE_UPDATES = 0;
UPDATE students1
SET marks = marks + 5;
SET SQL_SAFE_UPDATES = 1;
-- DELETE STUDENTS WITH MARKS < 50
DELETE FROM students1 WHERE marks < 50;