USE datatypes;
-- DEPARTMENT TABLE CREATED
CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50)
);
-- EMPLOYEES TABLE CREATED
CREATE TABLE EMPLOYEES(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY FLOAT,
ID INT,
FOREIGN KEY (ID)
REFERENCES DEPARTMENT(ID)
);
-- SHOW CREATED TABLES 
SHOW TABLES;
-- DESCRIBE TABLE
DESC EMPLOYEES;
DESC DEPARTMENT;