USE company_db;
-- PRACTICE SET 2
CREATE TABLE products(
id INT PRIMARY KEY,
name VARCHAR(50),
category VARCHAR(50),
price INT
);
-- INSERT 10 PRODUCTS
INSERT INTO products
VALUES
(1,"MOBILE PHONE","ELECTRONICS",15000),
(2,"EAR BUDS","ELECTRONICS",1000),
(3,"LAPTOP","ELECTRONICS",45000),
(4,"MONITOR","ELECTRONICS",7000),
(5,"OTT","ENTERTAINMENT",5000),
(6,"MAINTENANCE","ELECTRICITY",5000),
(7,"CAR","TRANSPORT",500000),
(8,"BIKE","TRANSPORT",100000),
(9,"WEAR","CLOTHING",10000),
(10,"FOOD","FOOD",5000);
-- DISPLAY PRODUCTS
SELECT * FROM products;
-- PRODUCT ABOVE 5000
SELECT * FROM products WHERE price > 5000;
-- ELECTRONIC PRODUCTS
SELECT * FROM products WHERE category = "ELECTRONICS";
-- PRODUCT BETWEEN 1000 AND 10000
SELECT * FROM products WHERE price < 10000 and price > 1000;
SELECT * FROM products WHERE price BETWEEN 1000 AND 10000;
-- PRODUCT NAME STARTING WITH M
SELECT * FROM products WHERE name LIKE "M%";
-- TOP 3 EXPENSIVE PRODUCTS
SELECT *
FROM products
ORDER BY PRICE DESC
LIMIT 3;
-- INCREASE ALL PRICES BY 10%
SET SQL_SAFE_UPDATES = 0;
UPDATE products
SET price = price * 1.10;
SET SQL_SAFE_UPDATES = 1;
-- DELETE PRODUCT BELOW 5000
DELETE FROM products
WHERE price < 5000;