USE datatypes;
/* STUDENT TABLE CREATION */
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);
/* COURSES TABLE CREATION */
CREATE TABLE COURSES(
COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(50),
ID INT,
FOREIGN KEY (ID)
REFERENCES STUDENT(ID)
);
/* DESCRIBE */
DESC STUDENT;
DESC COURSES;
/* SHOWING TABLES */
SHOW TABLES;